In [4]:
FILE_PATH = "./Data_Files/class1.txt"
f = open(FILE_PATH,"r")

In [20]:
def openClass():
    while True:
        filename = input("Enter name class: ") 
        FILE_PATH = "./Data_Files/" + filename + ".txt"
        try:
            f = open(FILE_PATH,"r+")
        except Exception as e:
            print(e)
        else:
            print("\n SUCCESSFULLY OPENED",filename)
            f.close()
            break

In [19]:
openClass()

Enter name class:  class1\

[Errno 2] No such file or directory: './Data_Files/class1\\.txt'

Enter name class:  class1

 SUCCESSFULLY OPENED
 class1

### Task 2
Nhiệm vụ của bạn cho phần này của chương trình là thực hiện như sau:

2.1. Báo cáo tổng số dòng dữ liệu được lưu trữ trong tệp.

2.2. Báo cáo tổng số dòng dữ liệu không hợp lệ trong tệp.

Một dòng hợp lệ chứa danh sách 26 giá trị được phân tách bằng dấu phẩy N# cho một học sinh là mục đầu tiên trên dòng. Nó phải chứa ký tự “N” theo sau là 8 ký tự số.

2.3. Nếu một dòng dữ liệu không hợp lệ, bạn nên báo cáo cho người dùng bằng cách in ra một thông báo lỗi.

Gợi ý: Sử dụng phương pháp split để tách dữ liệu ra khỏi tệp.

In [52]:
def analyzeClass():
    while True:
        filename = input("Enter name class: ") 
        FILE_PATH = "./Data_Files/" + filename + ".txt"
        try:
            f = open(FILE_PATH,"r+")
        except Exception as e:
            print(e)
        else:
            print("\n SUCCESSFULLY OPENED",filename)
            
        print("**** ANALYZING ****")
        k = 0 # number of lines
        error = 0 # number of lines error
        
        for line in f.readlines(): # Vòng lặp kiểm tra các lỗi của dữ liệu
            k += 1
            listValue = line.rstrip("\n").split(",")
            if len(listValue) != 26:
                print("Invalid line of data: does not contain exactly 26 values: \n")
                print(line,"\n")
                error += 1
            elif not listValue[0][1:].isnumeric() or len(listValue[0]) !=9:
                print("Invalid line of data: N# is invalid \n")
                print(line, "\n")
                error += 1
        if error == 0:
            print("No errors found!\n")
        
        print("**** REPORT ****\n")
        print("Total valid lines of data: ", k - error,"\n")
        print("Total invalid lines of data: ", error,"\n")

        choice = input("Do you want nhập thêm không? (0: không, 1: có)")
        
        if choice == "0":
            print("Goodbye - Thank you !")
            break

In [53]:
analyzeClass()

Enter name class:  class2

 SUCCESSFULLY OPENED class2
**** ANALYZING ****
Invalid line of data: does not contain exactly 26 values:

N00000023,,A,D,D,C,B,D,A,C,C,,C,,B,A,C,B,D,A,C,A,A


Invalid line of data: N# is invalid

N0000002,B,A,D,D,C,B,D,A,C,D,D,D,A,,A,C,D,,A,C,A,A,B,D,D


Invalid line of data: N# is invalid

NA0000027,B,A,D,D,,B,,A,C,B,D,B,A,,A,C,B,D,A,,A,A,B,D,D


Invalid line of data: does not contain exactly 26 values:

N00000035,B,A,D,D,B,B,,A,C,,D,B,A,B,A,A,B,D,A,C,A,C,B,D,D,A,A


**** REPORT ****

Total valid lines of data:  21

Total invalid lines of data:  4

Do you want nhập thêm không? (0: không, 1: có) 0

Goodbye - Thank you !

### Task 3
Chúng ta cũng cần thống kê các yêu cầu sau:

Đếm số lượng học sinh đạt điểm cao (>80.

Điểm trung bnh.

Điểm caonhất.

Điểm thp nhất.

Miền giá trị của điểm (cao nhất trừ tấp nhất).

Giá trị trung vị (Sắp xếp các điểm theo thứ tự tăng dần. Nếu # học sinh là số lẻ, bạn có thể lấy giá trị nằm ở giữa của tất cả các điểm (tức là [0, 50, 100] — trung vị là 50). Nếu # học sinh là chẵn bạn có thể tính giá trị trung vị bằng cách lấy giá trị trung bình của hai giá trị giữa (tức là [0, 50, 60, 100] — giá trị trungvị là 55)).

Trả về các câu hỏi bị học sinh bỏ qua nhiều nhất theo thứ tự: số thứ tự câu hỏi - số lượng học sinh bỏ qua - tỉ lệ bị bỏ qua (nếu có cùng số lượng cho nhiều câu hỏi bị bỏ thì phải liệt ê ra đầy đủ).

Trả về các câu hỏi bị học sinh sai qua nhiều nhất theo thứ tự: số thứ tự câu hỏi - số lượng học sinh trả lời sai - tỉ lệ bị sai (nếu có cùng số lượng cho nhiều câu hỏi bị sai thì phải liệt kê ra đầy đủ).

In [72]:
while True:
    filename = input("Enter name class: ") 
    FILE_PATH = "./Data_Files/" + filename + ".txt"
    try:
        f = open(FILE_PATH,"r+")
    except Exception as e:
        print(e)
    else:
        print("\n SUCCESSFULLY OPENED",filename)
        
    print("**** ANALYZING ****")
    k = 0 # number of lines
    error = 0 # number of lines error
    grade = [] # list grade
    valid_line = [] 
    answer_key = "B,A,D,D,C,B,D,A,C,C,D,B,A,B,A,C,B,D,A,C,A,A,B,D,D".split(",")

    for line in f.readlines(): # Vòng lặp kiểm tra các lỗi của dữ liệu
        k += 1
        listValue = line.rstrip("\n").split(",")
        if len(listValue) != 26:
            print("Invalid line of data: does not contain exactly 26 values: \n")
            print(line,"\n")
            error += 1
        elif not listValue[0][1:].isnumeric() or len(listValue[0]) !=9:
            print("Invalid line of data: N# is invalid \n")
            print(line, "\n")
            error += 1
        else:
            valid_line.append(listValue)
    
    for line in valid_line: # chấm điểm
        answer = line[1:]
        score = 0
        for j in range(25):
            if answer[j] == answer_key[j]:
                score += 4
            elif answer[j] == "":
                score += 0
            else:
                score -= 1 
        grade.append(score)

    if error == 0:
        print("No errors found!\n")

    print("**** REPORT ****\n")
    print("Total valid lines of data: ", k - error,"\n")
    print("Total invalid lines of data: ", error,"\n")
    print("Mean (average) score:", sum(grade)/len(grade),"\n")
    print("Highest score", max(grade),"\n")
    print("Lowest score", min(grade),"\n")
    print("Range of scores", max(grade) - min(grade),"\n")
    
    s = sorted(grade)
    n = len(grade)
    if n % 2 == 1:
        median = s[n//2] 
    else:
        median = sum(s[n//2 - 1: n//2 + 1])/2.0
        
    print("Median score: ",median,"\n")

    choice = input("Do you want nhập thêm không? (0: không, 1: có)")
    if choice == "0":
        print("Goodbye - Thank you !")
        break

Enter name class:  class1

 SUCCESSFULLY OPENED class1
**** ANALYZING ****
No errors found!

**** REPORT ****

Total valid lines of data:  20

Total invalid lines of data:  0

Mean (average) score: 75.6

Highest score 91

Lowest score 59

Range of scores 32

Median score:  73.0

Do you want nhập thêm không? (0: không, 1: có) 1
Enter name class:  class2

 SUCCESSFULLY OPENED class2
**** ANALYZING ****
Invalid line of data: does not contain exactly 26 values:

N00000023,,A,D,D,C,B,D,A,C,C,,C,,B,A,C,B,D,A,C,A,A


Invalid line of data: N# is invalid

N0000002,B,A,D,D,C,B,D,A,C,D,D,D,A,,A,C,D,,A,C,A,A,B,D,D


Invalid line of data: N# is invalid

NA0000027,B,A,D,D,,B,,A,C,B,D,B,A,,A,C,B,D,A,,A,A,B,D,D


Invalid line of data: does not contain exactly 26 values:

N00000035,B,A,D,D,B,B,,A,C,,D,B,A,B,A,A,B,D,A,C,A,C,B,D,D,A,A


**** REPORT ****

Total valid lines of data:  21

Total invalid lines of data:  4

Mean (average) score: 78.0

Highest score 100

Lowest score 66

Range of scores 34

Median score:  76

KeyboardInterrupt: Interrupted by user

### Task 4
Cuối cùng, yêu cầu chương trình là tạo một tệp “kết quả” chứa các kết quả chi tiết cho từng học sinh trong lớp. Mỗi dòng của tệp này phải chứa số ID của học sinh, dấu phẩy và sau đó là điểm của họ. Bạn nên đặt tên tệp này dựa trên tên tệp gốc được cung cấp — ví dụ: nếu người dùng chọn “class1.txt”, bạn nên lưu trữ kết quả trong tệp có tên “class1_grades.txt”.

In [79]:
while True:
    filename = input("Enter name class: ") 
    FILE_PATH = "./Data_Files/" + filename + ".txt"
    try:
        f = open(FILE_PATH,"r+")
    except Exception as e:
        print(e)
    else:
        print("\n SUCCESSFULLY OPENED",filename)
        
    print("**** ANALYZING ****")
    
    student_number = []
    grade = [] # list grade
    valid_line = [] 
    
    answer_key = "B,A,D,D,C,B,D,A,C,C,D,B,A,B,A,C,B,D,A,C,A,A,B,D,D".split(",")

    for line in f.readlines(): # Vòng lặp kiểm tra các lỗi của dữ liệu
        listValue = line.rstrip("\n").split(",")

        if len(listValue) == 26 and listValue[0][1:].isnumeric() and len(listValue[0]) == 9:
            valid_line.append(listValue)
    
    for line in valid_line: # chấm điểm
        student_number.append(line[0])
        answer = line[1:]
        
        score = 0
        for j in range(25):
            
            if answer[j] == answer_key[j]:
                score += 4
            elif answer[j] == "":
                score += 0
            else:
                score -= 1 
        grade.append(score)

    FILE_PATH_GRADE = "./Data_Files/" + filename + "_grade.txt"
    
    with open(FILE_PATH_GRADE,"w") as fw:
        for sn, gr in zip(student_number,grade):
            fw.write(sn + "," + str(gr) + "\n")
        print("Sucessfully write file " + filename + "_grade.txt \n")
    f.close()
    choice = input("Do you want input more? (0: không, 1: có)")
    if choice == "0":
        print("Goodbye - Thank you !")
        break

Enter name class:  class2

 SUCCESSFULLY OPENED class2
**** ANALYZING ****
Sucessfully write file class2_grade.txt

Do you want input more? (0: không, 1: có) 0

Goodbye - Thank you !

### Task 5
Chỉ sử dụng pandas và numpy, triển khai task 1 đến task 4.

In [1]:
import numpy as np
import pandas as pd

In [2]:
for i in range(1,9):
    FILE_PATH_DATA = "./Data_Files/class" + str(i) + ".txt"
    FILE_PATH_DATA_TASK_5 = "./Data_Files/class" + str(i) + "_task5.txt"
    
    with open(FILE_PATH_DATA,"r") as f:
        with open(FILE_PATH_DATA_TASK_5,"w") as fw:
            for line in f.readlines():
                listValue = line.rstrip("\n").split(",")
                if len(listValue) == 26 and listValue[0][1:].isnumeric() and len(listValue[0]) == 9:
                    fw.write(line)

In [3]:
while True:
    filename = input("Enter name class: ") 
    FILE_PATH = "./Data_Files/" + filename + "_task5.txt"
    try:
        df = pd.read_csv(FILE_PATH,delimiter=",",header = None, index_col=0)
        df.index.name = "student_number"
        df = df.fillna(0)
    except Exception as e:
        print(e)
    else:
        print("\n SUCCESSFULLY OPENED",filename)
        break;
df

 SUCCESSFULLY OPENED class1

,1,2,3,4,5,6,7,8,9,10,...,16,17,18,19,20,21,22,23,24,25
student_number,,,,,,,,,,,,,,,,,,,,,
N00000001,A,A,D,D,C,D,D,A,0,C,...,C,B,D,A,C,0,A,0,C,D
N00000002,0,A,0,D,0,B,D,A,C,C,...,C,B,D,C,C,A,A,B,0,D
N00000003,B,A,0,D,C,B,D,A,C,C,...,C,B,D,A,0,A,0,B,D,D
N00000004,B,B,D,0,0,B,D,A,C,C,...,C,B,D,0,C,A,D,B,C,D
N00000005,B,A,0,D,0,B,D,A,C,C,...,C,B,D,D,C,A,A,0,D,D
N00000006,B,A,D,A,C,B,D,A,C,C,...,C,0,C,A,C,A,C,B,D,A
N00000007,B,A,D,D,C,B,D,A,C,0,...,C,B,D,0,C,A,A,B,D,0
N00000008,A,A,D,D,C,0,D,A,C,C,...,A,B,D,A,C,A,0,B,B,D
N00000009,B,A,0,D,C,B,D,A,C,A,...,A,B,D,A,C,A,A,B,D,D
N00000010,0,A,D,B,C,B,D,A,C,C,...,C,B,D,A,D,0,0,B,D,B
N00000011,B,A,D,0,C,B,D,A,C,D,...,C,B,D,A,C,A,B,B,D,D
N00000012,B,0,D,D,C,B,D,A,C,C,...,A,B,D,A,0,A,A,A,0,C
N00000013,0,A,D,0,B,B,0,A,C,A,...,C,B,D,A,C,A,A,B,D,D
N00000014,B,B,D,D,C,B,0,D,C,C,...,C,0,D,A,C,A,A,0,D,D
N00000015,A,C,C,D,C,B,0,A,C,C,...,C,B,D,A,C,A,B,0,D,D
N00000016,B,A,C,D,0,B,D,A,C,C,...,C,B,D,A,C,A,A,B,D,D
N00000017,B,A,D,D,C,B,C,A,D,C,...,C,B,D,D,B,0,A,B,D,D
N00000018,B,A,D,A,C,B,D,A,C,C,...,0,B,D,A,B,A,A,B,0,D
N00000019,B,A,D,D,C,B,D,C,C,C,...,C,B,D,A,0,A,A,B,D,D
N00000020,B,0,D,D,C,B,D,A,C,B,...,D,B,D,B,C,A,A,B,D,D

In [4]:
while True:
    filename = input("Enter name class: ") 
    FILE_PATH = "./Data_Files/" + filename + "_task5.txt"
    try:
        df = pd.read_csv(FILE_PATH,delimiter=",",header = None, index_col=0)
        df.index.name = "student_number"
        df = df.fillna(0)
    except Exception as e:
        print(e)
    else:
        print("\n SUCCESSFULLY OPENED",filename)
        break

grade = [] # list grade

answer_key = "B,A,D,D,C,B,D,A,C,C,D,B,A,B,A,C,B,D,A,C,A,A,B,D,D".split(",")

for i in range(df.shape[0]):
    score = 0
    for j in range (df.shape[1]):
        if df.iloc[i,j] == answer_key[j]:
            score += 4
        elif df.iloc[i,j] == 0:
            score += 0
        else:
            score -= 1
    grade.append(score)
    
df["score"] = grade


print("**** REPORT ****\n")
print("Total valid lines of data: ", df.shape[0],"\n")
print("Mean (average) score:", df["score"].mean(),"\n")
print("Highest score", df["score"].max(),"\n")
print("Lowest score", df["score"].min(),"\n")
print("Range of scores", df["score"].max() - df["score"].min(),"\n")
print("Median score: ",df["score"].median(),"\n")

 SUCCESSFULLY OPENED class1
**** REPORT ****

Total valid lines of data:  20

Mean (average) score: 75.6

Highest score 91

Lowest score 59

Range of scores 32

Median score:  73.0